@channel_seeds = [
    {"url"=>"https://www.youtube.com/@mbsnews", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@tvosakanews", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@htbnews", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@CHUKYOTV_NEWS", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@NagoyaTVnewsCH", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@khb", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@habmigochannel", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@cbctv_news", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@SankeiNews", "categories" => %w(politics technology economy sports)},
    {"url"=>"https://www.youtube.com/@watanabetetuya-show", "categories" => %w(politics economy military sports)},
    {"url"=>"https://www.youtube.com/@aichi-news", "categories" => %w(economy technology business military sports)},
    {"url"=>"https://www.youtube.com/@ThepageJp", "categories" => %w(politics economy military sports technology)},
    {"url"=>"https://www.youtube.com/@newsone4365", "categories" => %w(politics economy military sports technology)},
    {"url"=>"https://www.youtube.com/@ytv_news", "categories" => %w(politics economy world trend sports)},
    {"url"=>"https://www.youtube.com/@News_ABEMA", "categories" => %w(politics economy world military trend sports)},
    {"url"=>"https://www.youtube.com/@nikkanshunshun", "categories" => %w(politics economy world military trend sports)},
    {"url"=>"https://www.youtube.com/@toranomonnews", "categories" => %w(politics economy world military trend sports)},
    {"url"=>"https://www.youtube.com/@user-le9qv3yz9r", "categories" => %w(politics economy world military trend sports)},
    {"url"=>"https://www.youtube.com/@ntv_news", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@ANNnewsCH", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@FNNnewsCH", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@tbsnewsdig", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@KyodoNews", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@prime_ABEMA", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@tvtokyobiz", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@abc6ch", "categories" => %w(politics technology economy world sports)},
    {"url"=>"https://www.youtube.com/@takaponjp", "categories" => %w(politics technology economy world sports)},

    {"url"=>"https://www.youtube.com/@ChGrandStrategy", "categories" => %w(politics technology economy world military)},
    {"url"=>"https://www.youtube.com/@ReutersJapan", "categories" => %w(world economy technology)},
    {"url"=>"https://www.youtube.com/@NikkeiCNBC", "categories" => %w(economy technology military equity_investment)},

    {"url"=>"https://www.youtube.com/@NewsPicks", "categories" => %w(business technology)},
    {"url"=>"https://www.youtube.com/@diy4600", "categories" => %w(politics economy)},
    {"url"=>"https://www.youtube.com/@tsj_otb", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@milirepo", "categories" => %w(politics economy)},
    {"url"=>"https://www.youtube.com/@user-uy4cr9se8j", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@maomao96363", "categories" => %w(politics world)},
    {"url"=>"https://www.youtube.com/@oikawa_yukihisa1", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@kazuyachgx", "categories" => %w(politics economy)},
    {"url"=>"https://www.youtube.com/@WWUK_TV", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@news_sokuho", "categories" => %w(politics)},
    {"url"=>"https://www.youtube.com/@TsukasaJonen", "categories" => %w(politics)},
    {"url"=>"https://www.youtube.com/@BBCNewsJapan", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@Invest_and_Living", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@primenews/", "categories" => %w(world politics military)},
    {"url"=>"https://www.youtube.com/@news_8ch", "categories" => %w(politics)},
    {"url"=>"https://www.youtube.com/@JAPANnpj", "categories" => %w(politics)},
    {"url"=>"https://www.youtube.com/@suntv_news_Japan", "categories" => %w(politics other)},
    {"url"=>"https://www.youtube.com/@Bungeishunju", "categories" => %w(politics military)},
    {"url"=>"https://www.youtube.com/@skoichi", "categories" => %w(politics trend)},
    {"url"=>"https://www.youtube.com/@shigoto", "categories" => %w(business work)},
    {"url"=>"https://www.youtube.com/@USAMilitaryChannel2", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@gototatsuya", "categories" => %w(economy)},
    {"url"=>"https://www.youtube.com/@SuntvCoJp_ohsun", "categories" => %w(sports technology)},
    {"url"=>"https://www.youtube.com/@seikeidenronTV", "categories" => %w(business politics)},
    {"url"=>"https://www.youtube.com/@user-td7uu8sb7u", "categories" => %w(politics)},
    {"url"=>"https://www.youtube.com/@3.0", "categories" => %w(politics economy world)},
    {"url"=>"https://www.youtube.com/@DEEPMAX", "categories" => %w(politics economy)},
    {"url"=>"https://www.youtube.com/@takahashi_yoichi", "categories" => %w(business politics economy world)},
    {"url"=>"https://www.youtube.com/@mykey-sano", "categories" => %w(business politics technology economy)},
    {"url"=>"https://www.youtube.com/@mitsuhashipress", "categories" => %w(politics economy world)},
    {"url"=>"https://www.youtube.com/@FIFIchannel", "categories" => %w(politics economy world)},
    {"url"=>"https://www.youtube.com/@kazuyachgx", "categories" => %w(politics economy world)},
    {"url"=>"https://www.youtube.com/@user-rb3pn7uz3m", "categories" => %w(politics economy world)},
    {"url"=>"https://www.youtube.com/@mofmof-investor", "categories" => %w(politics economy business sports money_finance)},
    
    {"url"=>"https://www.youtube.com/@user-du7gi7mt4w", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@user-xb3px7to3b", "categories" => %w(world)},
    {"url"=>"https://www.youtube.com/@yoakemaeplayers", "categories" => %w(world)},
    
    {"url"=>"https://www.youtube.com/@monozukuritarou", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@erestage", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@Ch-dp9or", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@YamatoNadeshiko", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@nex.kougyo", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@stec1124", "categories" => %w(technology)},
    {"url"=>"https://youtube.com/@semiconductor-industry", "categories" => %w(technology)},
    {"url"=>"https://www.youtube.com/@AMANOSCOPE", "categories" => %w(technology business)},
    {"url"=>"https://www.youtube.com/@remote-work", "categories" => %w(technology business)},
    {"url"=>"https://www.youtube.com/@bouncy", "categories" => %w(technology business)},
    {"url"=>"https://www.youtube.com/@nikkei", "categories" => %w(business technology)},

    {"url"=>"https://www.youtube.com/@manabusiness", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@honmanachannel", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@pivot8935", "categories" => %w(business, technology)},
    {"url"=>"https://www.youtube.com/@sam-book", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@sonsera_ch", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@gakushikisaron", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@shin_R25", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@salatame", "categories" => %w(business lifehack)},
    {"url"=>"https://www.youtube.com/@ryukkebibinnba", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@nensyu_channel", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@tabbata", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@MABANK2018", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@YoshikiOkamotoWorkshop", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@oohorisouta-doruma", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@user-cb7xb1lh2m", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@flier6114", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@rehacq", "categories" => %w(business world politics)},
    {"url"=>"https://www.youtube.com/@user-hr1by4lc1w", "categories" => %w(business world politics)},
    {"url"=>"https://www.youtube.com/@tomomura", "categories" => %w(business technology)},
    {"url"=>"https://www.youtube.com/@webshokutv", "categories" => %w(business technology)},
    {"url"=>"https://www.youtube.com/@kidsnastyle", "categories" => %w(business)},
    {"url"=>"https://www.youtube.com/@yasabi-jp", "categories" => %w(business)},

    {"url"=>"https://www.youtube.com/@gunjitsuushin", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@USAMilitaryChannel2", "categories" => %w(military technology)},
    {"url"=>"https://www.youtube.com/@world-military", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@nihongunji", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@gunjitimes", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@user-wg8yz1iw2m", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@gunji-puress", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@yukkurigunjinews", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@himarianri", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@user-bd2zz8di8q", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@user-ur6kq7jy2q", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@user-ed7kj2yg1y", "categories" => %w(military)},
    {"url"=>"https://www.youtube.com/@milirepo", "categories" => %w(military)},

    {"url"=>"https://www.youtube.com/@user-ys8zx2om4s", "categories" => %w(weopon)},
    {"url"=>"https://www.youtube.com/@weapondou", "categories" => %w(weopon)},
    {"url"=>"https://www.youtube.com/@Dangan_D_March", "categories" => %w(military weopon), "absolute"=> %w(weopon)},
    {"url"=>"https://www.youtube.com/@c-labo-japanesemilitaryinf1328", "categories" => %w(weopon)},
    {"url"=>"https://www.youtube.com/@YoshikiOkamotoWorkshop", "categories" => %w(weopon)},

    {"url"=>"https://www.youtube.com/@cabbage_games", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@YoshikiOkamotoGameCh", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@sora_sakurai_jp", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@OYAYUVI", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@gameyawa", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@user-ys6bh5zc3k", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@gameyawa", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@dengekionline", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@nakaido", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@midnight_chimau", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@NintendoJP", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@PlayStationJapan", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@ichigo_Gamebeat", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@capcom", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@squareenix", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@NayneGamez", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@chomes3104", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@keiji_ch", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@automatonchannel", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@pandaiku", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@steamharachin", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@stmatomato", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@yamachan-game-giriikiteru", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@-ch-qx5lh", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@odesigame", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@omigames", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@akagitotoro", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@kotoragame", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@kentworldg", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@D_Galle", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@SmithAndGames", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@kelloggsan_tv", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@user-mv5lu2lq9t", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@bandainamcoentertainment", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@FromSoftwareInc", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@aoigame-ch", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@user-tg9vx1ev4z", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@denfami", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@Pinpuro", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@silesaaa", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@ginjogames", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@murasetairu", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@bakyunBP", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@user-xd9qc2rz4w", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@moshimo", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@steamharachin", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@martin_games", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@gogofunassy", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@NagayuGame", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@hattori2021", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@arayangame", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@switchsuposhi", "categories" => %w(game)},
    {"url"=>"https://www.youtube.com/@hagu-meta", "categories" => %w(game)},
    
    {"url"=>"https://www.youtube.com/@hiyoko246", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@sakki-tvch", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@ttmtsuyoshi", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@kasukabesouzoku", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@ryohin", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@sasayan", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@motomitsu", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@pukujiji", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@kureanews_2", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@user-yz3ti4lf3m", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@gaguru.tubenews", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@chouekitarou893", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@bunshun_kisha", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@Mikoneko2023", "categories" => %w(trend)},
    {"url"=>"https://www.youtube.com/@ArcTimes1", "categories" => %w(trend world)},
    {"url"=>"https://www.youtube.com/@yukoreadman", "categories" => %w(trend politics)},
    {"url"=>"https://www.youtube.com/@mobile_game_AK", "categories" => %w(trend politics)},

    {"url"=>"https://www.youtube.com/@SonyXperia", "categories" => %w(gadget tour)},
    {"url"=>"https://www.youtube.com/@kentworldg", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@MrVR", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@ArimaxVR", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@mirais_vr", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@YamatoNadeshiko", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@Takomaruuun", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@gizmodojapan", "categories" => %w(gadget technology)},
    {"url"=>"https://www.youtube.com/@takahashiyamada", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@yoshidaaaaaaaaaaaaaaaaaaaaaaaa", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@ThomasGadgemaga", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@harukanachannel", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@sumasapo", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@masaru1088", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@rbbtodaycom", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@WatanabeKazumasa", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@SGRT3rd", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@ToviWorks", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@gazyekichi", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@Yuta_Hiraoka", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@MonogamaGadget", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@tobalog_toba", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@RecPlus", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@masaru1088", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@Usyasuraimu", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@kajimack", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@shinkichi39", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@rebecca_miyama", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@yamako_mini_free", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@daiking3", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@monograph_", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@nikostyle_tk", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@mamiyoshi", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@yuji-lifehack", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@kisuke", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@monograph_", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@todasatoru", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@appleshinja-1okuninn", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@imamura4k", "categories" => %w(gadget)},
    {"url"=>"https://www.youtube.com/@zattavr", "categories" => %w(gadget game technology)},
    


    {"url"=>"https://www.youtube.com/@oshare_iruka", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@smappy_channel", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@mori_house", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@mujio_mujirushi", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@MiD.", "categories" => %w(necessity gadget)},
    {"url"=>"https://www.youtube.com/@muji_hayashi", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@resky_ch", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@laffic", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@manmalunaLifeVlog", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@sukinamon", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@mlife.puchipura", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@miniminidiarist", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@100-channel", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@kurashikata", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@mai.minimalism", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@nylonpoly_outdoor", "categories" => %w(necessity womens_fashion)},
    {"url"=>"https://www.youtube.com/@youyaku", "categories" => %w(lifehack business)},
    {"url"=>"https://www.youtube.com/@booksumbook", "categories" => %w(lifehack business)},
    {"url"=>"https://www.youtube.com/@abst", "categories" => %w(lifehack business)},
    {"url"=>"https://www.youtube.com/@nomonomolife", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@kurashi_style", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@kinocco", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@KUMALOG_YAMAGOYA", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@haruchannel3", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@imasarachannel", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@lululog9627", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@j-log8430", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@takabon", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@ichi_mama", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@shinoschannel", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@sanu_home", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@my-room", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@nuecohome", "categories" => %w(necessity)},
    {"url"=>"https://www.youtube.com/@minchi_pooh", "categories" => %w(necessity)},

    {"url"=>"https://www.youtube.com/@kazuch0924", "categories" => %w(necessity gadget)},
    {"url"=>"https://www.youtube.com/@sumasapo", "categories" => %w(necessity gadget)},
    {"url"=>"https://www.youtube.com/@thedadsecretbase", "categories" => %w(gadget necessity stationary)},
    {"url"=>"https://www.youtube.com/@SagaraGouchi", "categories" => %w(gadget necessity)},
    {"url"=>"https://www.youtube.com/@COM_Gadget", "categories" => %w(gadget necessity)},
    {"url"=>"https://www.youtube.com/@king.blog05", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@Lifelogtube", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@user-et8nn1rk7i", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@natsuko271", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@natsuko271", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@hiyo0205", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@LifeStyleJournal_saku", "categories" => %w(lifehack necessity)},
    {"url"=>"https://www.youtube.com/@iamahousewife", "categories" => %w(necessity lifehack cooking)},
    {"url"=>"https://www.youtube.com/@nnnhome-nonbiri", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@leprium", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@latte_house", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@samia.housework", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@uchilog", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@megulife7223", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@nanaoakiko", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@chi.yu_", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@KEINA.", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@minimalistpaik", "categories" => %w(necessity lifehack)},
    {"url"=>"https://www.youtube.com/@yamamomoda4", "categories" => %w(necessity womens_fashion)},
    {"url"=>"https://www.youtube.com/@inlivingjp", "categories" => %w(necessity womens_fashion)},
    {"url"=>"https://www.youtube.com/@COM_Gadget", "categories" => %w(necessity gadget)},
    
    {"url"=>"https://www.youtube.com/@communication_cafe", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@sakurabookmarks", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@nanahachi_bungu", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@techoutime", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@seasar04", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@Shigoto_no_Kodougu", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@HEROTV_stationery", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@user-hf7kg9pi8u", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@yuzu_stationery_store", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@Shigoto_no_Kodougu", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@ORC_stationery", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@merin123", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@pomenote", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@Shobou", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@merin123", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@holidaytime9563", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@MiiCHOS", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@syamcco6393", "categories" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@techoutime", "categories" => %w(lifehack stationary), "absolute" => %w(stationary)},
    {"url"=>"https://www.youtube.com/@inmyroomnote", "categories" => %w(stationary lifehack)},
    {"url"=>"https://www.youtube.com/@Yurindo_YouTube", "categories" => %w(stationary necessity)},
    {"url"=>"https://www.youtube.com/@creamsoda-log", "categories" => %w(stationary lifehack)},
    {"url"=>"https://www.youtube.com/@kana.note_", "categories" => %w(stationary lifehack)},
    {"url"=>"https://www.youtube.com/@diary3582", "categories" => %w(stationary lifehack)},
    {"url"=>"https://www.youtube.com/@MakoIkeda", "categories" => %w(lifehack necessity)},

    {"url"=>"https://www.youtube.com/@MiorinCafe", "categories" => %w(stationary study)},
    {"url"=>"https://www.youtube.com/@communication_cafe", "categories" => %w(study)},


    {"url"=>"https://www.youtube.com/@user-lp1bg4qq7i", "categories" => %w(mobitity technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@jimny_kozakura", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@wansokutube", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@KG_motors", "categories" => %w(mobility technology)},
    {"url"=>"https://www.youtube.com/@AMCacademic", "categories" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@bokutes", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@kuhlracingtv906", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@user-sw8wr3xq1l", "categories" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@yumiyoshida439", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@toyotatimes", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@driverchannel", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@newcarlife", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@kuruma_yukkuri", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    {"url"=>"https://www.youtube.com/@kurumalove-kenkyujyo", "categories" => %w(mobility technology), "absolute" => %w(mobility)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(mobility)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(mobility)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(mobility)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(mobility)},
    
    {"url"=>"https://www.youtube.com/@hayatasuuu", "categories" => %w(sales)},
    {"url"=>"https://www.youtube.com/@KiyotoUniv", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@pythonvtuber9917", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@TECHWORLD111", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@kentatv2710", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@engineer_first", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@webit7652", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@it_bosatsu_moro", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@user-pl5cc5hs5m", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@ara_sun_", "categories" => %w(engineer)},
    {"url"=>"https://www.youtube.com/@SES_CH", "categories" => %w(engineer)},

    {"url"=>"https://www.youtube.com/@sokketsu", "categories" => %w(sales)},
    {"url"=>"https://www.youtube.com/@SES_CH", "categories" => %w(sales)},
    {"url"=>"https://www.youtube.com/@SES_CH", "categories" => %w(sales)},
    {"url"=>"https://www.youtube.com/@SES_CH", "categories" => %w(sales)},
    #{"url"=>"https://www.youtube.com/@takehana_minds", "categories" => %w(切り抜き)},
    #{"url"=>"https://www.youtube.com/@honmanachannel", "categories" => %w(切り抜き)},
    #{"url"=>"https://www.youtube.com/@honmanachannel", "categories" => %w(切り抜き)},
    #{"url"=>"https://www.youtube.com/@honmanachannel", "categories" => %w(切り抜き)},
    {"url"=>"https://www.youtube.com/@numtr", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@youseful_skill", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@tmchannel1115", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@yukipedia", "categories" => %w(lifehack business)},
    {"url"=>"https://www.youtube.com/@ofumi_3", "categories" => %w(lifehack necessity womens_fashion)},
    {"url"=>"https://www.youtube.com/@ima247", "categories" => %w(lifehack money_finance womens_fashion)},
    {"url"=>"https://www.youtube.com/@hikopro6723", "categories" => %w(lifehack necessity gadget)},
    {"url"=>"https://www.youtube.com/@mususuma", "categories" => %w(lifehack gadget)},
    {"url"=>"https://www.youtube.com/@AppleJapan", "categories" => %w(lifehack other)},
    {"url"=>"https://www.youtube.com/@tanapi_fufu385", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@mizuna_mama", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@soeasy", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@makonari_shacho", "categories" => %w(lifehack business)},
    {"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@taiki007", "categories" => %w(lifehack technology)},
    {"url"=>"https://www.youtube.com/@nbaku", "categories" => %w(lifehack work)},
    {"url"=>"https://www.youtube.com/@saisuma-yoshida", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@sinminimallife", "categories" => %w(lifehack money_finance)},
    {"url"=>"https://www.youtube.com/@curama_univ.", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@osouji-taro", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@gamaguchi-fire", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@tsukiko_kitchen", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@pro_osouji", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@osayosan34", "categories" => %w(lifehack other)},
    {"url"=>"https://www.youtube.com/@zuboramame", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@yune__room", "categories" => %w(lifehack diy)},

    {"url"=>"https://www.youtube.com/@katsuma_kazuyo", "categories" => %w(life)},

    {"url"=>"https://www.youtube.com/@fuyuko_money", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@yukkuri-money", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@fpinoue", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@koala.t", "categories" => %w(economy world money_finance)},
    {"url"=>"https://www.youtube.com/@kakemane", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@bankacademy", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@amamura-sohsei", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@tokumoney", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@onizukayuichi", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-by9it9pm5x", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@mari9599", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@peach.setsuyaku", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@setuyakuoneesan", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-xj7uz3oh5s", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@yuminyan_mini", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@rico-family", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-td7bz1cu6n", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@wts_rio", "categories" => %w(money_finance other)},
    {"url"=>"https://www.youtube.com/@kuchan1981", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@sio__tube", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-xj7uz3oh5s", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@kentaro_saving", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@enjoychannel5445", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-et5ig8ue6f", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@motocook__", "categories" => %w(money_finance cooking)},
    {"url"=>"https://www.youtube.com/@user-nv9uj7ts2x", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@ryogakucho", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@beneficial-2ch-money", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@MoneySenseCollege", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-ox7ss6vy1h", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@money_time_school", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@sos9608", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@riko-channel", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@otakuCPA", "categories" => %w(ife_finance)},
    {"url"=>"https://www.youtube.com/@allabout6072", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@by_myself", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@sr.nakamura", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@hidakuma-kakeikanri", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@money-institute", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@nenkin_ch", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@senior_savings_lab", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@moneynotetsujin.chacha", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-mb5rx2pf4m", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@healthcare_uni", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@around_retire", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@zeirishiyoutuber", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@mikata-c", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@zukaidemanabu", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@kentaro_saving", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@ralph.fire.2034", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@user-hx7bn7hp9v", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@nasubimoney", "categories" => %w(money_finance)},
    {"url"=>"https://www.youtube.com/@rin_ouchi_gohan", "categories" => %w(money_finance cooking)},
    {"url"=>"https://www.youtube.com/@ryogakucho", "categories" => %w(money_finance business)},
    {"url"=>"https://www.youtube.com/@kikinurse", "categories" => %w(money_finance necessity lifehack)},
    {"url"=>"https://www.youtube.com/@Mochi.minimum", "categories" => %w(money_finance necessity womens_fashion lifehack)},
    {"url"=>"https://www.youtube.com/@master-of-money", "categories" => %w(money_finance lifehack)},
    {"url"=>"https://www.youtube.com/@ichientaro", "categories" => %w(money_finance business lifehack)},
    {"url"=>"https://www.youtube.com/@user-of4ik2zu9n", "categories" => %w(money_finance necessity)},
    {"url"=>"https://www.youtube.com/@MinimalistTakeru", "categories" => %w(money_finance lifehack)},


    {"url"=>"https://www.youtube.com/@sunday-money", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@yutorihuhunochokinron", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@buffett_taro", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@bacchama", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@Monexondemand", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@yukkuri-losscut", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@FinancialCamp", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@tesuta-clipping", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@tsumitateman", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@Tomostockinvestment", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@USStockhanako", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@pan-invest", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@yohei-chokin", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@toshi_anime", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@yukimizu4972", "categories" => %w(equity_investment lifehack)},
    {"url"=>"https://www.youtube.com/@WATUSinvestor", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@DanTakahashi1", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kabunokaidoki", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kabu-daytrade", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kakeroom_com", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@riku_inv_ex", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@umiharajp", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kamioka01", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@SHO1112", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@tapazou29", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@ToshiruRsec", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@toushikomon", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@SLokRE", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@user-rk2cj8ro8v", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@user-vz4kr9yu8p", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@JoeTakayama", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@Legend_of_SP500", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@news7511", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@1up79", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@makabee7", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kabu.moriguchi", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@ga-ko", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@shibaton_money", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@mabuchi-mariko", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kasahara_sonshi", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@SATOPON-nisa", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@tora-san", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@investor-Horie", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@world_company", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@1okuenbusinesscollege", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@MATCH-TV29", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@kunizemi", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@yutaikabu", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@imagawamoneyschool2020", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@user-ik9tw2bc2c", "categories" => %w(equity_investment money_finance)},
    {"url"=>"https://www.youtube.com/@invest_study", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@info_ask1", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@dekoboko104", "categories" => %w(equity_investment)},
    {"url"=>"https://www.youtube.com/@dekoboko104", "categories" => %w(equity_investment)},

    {"url"=>"https://www.youtube.com/@yosukefudosan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@kabunokaidoki", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@saki_kaigaihudousan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@rakumachi", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@mansiontaro", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@mackey-estate", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@YukkuriFudosan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@gmentakishima", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@koharamasanori", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@shisankeisei-channel", "categories" => %w(real_estate_investment money_finance equity_investment)},
    {"url"=>"https://www.youtube.com/@terass_sumai_academy", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@user-zq2mq7mt5c", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@urakenfudosan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@user-ly7mz6hk5o", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@surferyaku", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@yosukefudosan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@ayukawa-tv", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@landsitz3738", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@bbri-fudosan", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@user-bo1tb2jd4f", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@uruchukai", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@yamautis1", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@tanaka130", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@user-pr3xo4hb3z", "categories" => %w(real_estate_investment)},
    {"url"=>"https://www.youtube.com/@youtube_fudousan", "categories" => %w(real_estate_investment)},

    {"url"=>"https://www.youtube.com/@_anariso_", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@YukkuriFudosan", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@itsudemofudosan", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@RoomPa", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@mahalohouse.fukuoka", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@kusegatuyoiestate", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@_anariso_", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@bruno9272", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@MikanfudousanRoomTourWithMICAN", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@Roommy_Roomtour", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@naikenchannel", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@j0hnny00", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@ApartmentLabo", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@akiyayan", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@fukkaru", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@yourlifeviewing", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@Womanchannel", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@SamuraiWinWinHOME", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@designhouse_desie", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@Ghouse-osaka", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@ootori8", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@sunpro36", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@winghome_youtube", "categories" => %w(property)},
    {"url"=>"https://www.youtube.com/@Collabohouse1234", "categories" => %w(property)},

    {"url"=>"https://www.youtube.com/@DIY_OTAKU_take", "categories" => %w(diy)},

    {"url"=>"https://www.youtube.com/@MatsuiSecurities", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@TAKA_FX", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fx7708", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fx8425", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@gaitamesk_com", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@kojikoji-FX", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fxdoruenn", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fx.naotoretv", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@Mayohare-fx", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fxchannel3188", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@sbifxt_official", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@gaitame_com", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@naminoridojo", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fxchannel3188", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fxbo9629", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fuuta_fx", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fxyosuga", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@TheMovingAverageJP", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(fx_trade)},
    {"url"=>"https://www.youtube.com/@harris.investor", "categories" => %w(fx_trade business cryptocurrency)},

    {"url"=>"https://www.youtube.com/@Joe_Web3", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@fujimana", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@user-hl4vt6tf5h", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@user-fq9er3we3i", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@FX-pr4zp", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@crypto-bonbon", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@user-gn8qb7by6y", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@StarShunX", "categories" => %w(cryptocurrency)},
    {"url"=>"https://www.youtube.com/@traderkant", "categories" => %w(cryptocurrency)},

    {"url"=>"https://www.youtube.com/@xshow7", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@tom_about_sns", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@user-xf6lq5lj4x", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@yuimama", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@zero-kigyou-fukugyou", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@xshow7", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@Kotaro-channel0467", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@sayaka8758", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@Money.school", "categories" => %w(new_job money_finance)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@fx-4332", "categories" => %w(new_job)},
    {"url"=>"https://www.youtube.com/@abemutsuki", "categories" => %w(lifehack new_job)},

    {"url"=>"https://www.youtube.com/@jin115xx", "categories" => %w(fx equity_investment)},
    {"url"=>"https://www.youtube.com/@keitasasaki", "categories" => %w(cryptocurrency equity_investment)},

    {"url"=>"https://www.youtube.com/@bysbi4805", "categories" => %w(lifehack new_job fx equity_investment)},

    {"url"=>"https://www.youtube.com/@Python_VBA", "categories" => %w(lifehack_tool web)},


    {"url"=>"https://www.youtube.com/@hiroyukikirinuki", "categories" => %w(hiroyuki trend)},
    {"url"=>"https://www.youtube.com/@hiroyukimind", "categories" => %w(hiroyuki)},
    {"url"=>"https://www.youtube.com/@Hiroyuke", "categories" => %w(hiroyuki trend necessity carrer)},
    {"url"=>"https://www.youtube.com/@hironuki", "categories" => %w(hiroyuki trend)},
    #{"url"=>"https://www.youtube.com/@erutorecruit", "categories" => %w(mobilityrer)},
    #{"url"=>"https://www.youtube.com/@3utsu", "categories" => %w(lifehack)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(lifehack)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(lifehack)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(lifehack)},
    #{"url"=>"https://www.youtube.com/@kazokushuno", "categories" => %w(lifehack)},
    {"url"=>"https://www.youtube.com/@2ch_yueki_5ch", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-sg6zr", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-matome", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@shuuuukatu", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@d-niki", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@ch-nz7yk", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@obaka-matome", "categories" => %w(board carrer)},
    {"url"=>"https://www.youtube.com/@2ch-matome", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2chlab", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2chyu-eking", "categories" => %w(board lifeevent)},
    {"url"=>"https://www.youtube.com/@2chNanJ", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@ch-lb8yr", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-kisoutengai", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@Tetsujin28hiki", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@ch-bs9es", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@yukkuri-waraeru", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@nanJsokutu", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@user-zl9js6pf9w", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-qt9jp", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2chsyukatu", "categories" => %w(board carrer)},
    {"url"=>"https://www.youtube.com/@2ch2ch5ch4", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-ga-sukinandao", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@pokomake", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch612", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2chNanJ", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch2ch5ch4", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@5ch_neko", "categories" => %w(board comedy)},
    {"url"=>"https://www.youtube.com/@ch-kq2mm", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch_dobutsu", "categories" => %w(board animal)},
    {"url"=>"https://www.youtube.com/@2ch-sukatto", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@user-en5ci1hs3k", "categories" => %w(board lifehack)},
    {"url"=>"https://www.youtube.com/@user-uj1gt5yj1y", "categories" => %w(board lifehack beauty)},
    {"url"=>"https://www.youtube.com/@user-qm5tv6vs7e", "categories" => %w(board lifehack beauty)},
    {"url"=>"https://www.youtube.com/@matomegirlsch", "categories" => %w(board lifehack beauty)},
    {"url"=>"https://www.youtube.com/@girls-zarashi-ch", "categories" => %w(board lifehack beauty)},
    {"url"=>"https://www.youtube.com/@girls-cosme", "categories" => %w(board beauty)},
    {"url"=>"https://www.youtube.com/@user-rf9ci6tl4r", "categories" => %w(board beauty)},
    
    {"url"=>"https://www.youtube.com/@unnamedch", "categories" => %w(carrer)},


    {"url"=>"https://www.youtube.com/@nanJdx", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@tarutaru2ch", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2chdokaguibu", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@Apparech", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch195", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch300", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@rice2ch", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@waraerusyo-to", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@horrorro-adshowchannel", "categories" => %w(board)},
    {"url"=>"https://www.youtube.com/@2ch-omoshiro-short", "categories" => %w(board)},
    

    
    {"url"=>"https://www.youtube.com/@ninninkyo", "categories" => %w(education)},
    {"url"=>"https://www.youtube.com/@takashi_ch", "categories" => %w(education)},
    {"url"=>"https://www.youtube.com/@2ch-omoshiro-short", "categories" => %w(education)},
    {"url"=>"https://www.youtube.com/@tokyo-shoten", "categories" => %w(education)},

    {"url"=>"https://www.youtube.com/@2ch-omoshiro-short", "categories" => %w(education)},
    {"url"=>"https://www.youtube.com/@yoshi-koba", "categories" => %w(education lifehack business)},
    {"url"=>"https://www.youtube.com/@Aba_Book_Tuber", "categories" => %w(education)},


    {"url"=>"https://www.youtube.com/@featch3622", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@cellbank-TV", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@user-ng2tp5jm9i", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@aratatomori", "categories" => %w(beauty health)},
    {"url"=>"https://www.youtube.com/@kazunosuke", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@sakimegu_beauty", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@user-tu9pg1ct7x", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@hirobeautychannel", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@MarilynFukuseYuuri", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@345chan", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@775nanako", "categories" => %w(beauty womens_fashion)},
    {"url"=>"https://www.youtube.com/@ashinoura_makeup", "categories" => %w(beauty necessity)},
    {"url"=>"https://www.youtube.com/@mizukoshimisato", "categories" => %w(beauty necessity womens_fashion)},
    {"url"=>"https://www.youtube.com/@user-ro6gx4nk9e", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@hashimotobeautychannel452", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@_yoshida_akari", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@sizzle-tv", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@VOCE", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@tsumikibeauty", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@CosmeWotaSara", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@sayuri-makeup", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@ASMRCosmeticRepair", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kayoko_yazaki", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@ninamori1160", "categories" => %w(beauty womens_fashion)},
    {"url"=>"https://www.youtube.com/@pinkbuyer", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@smishow01", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kayocosme", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@EGA.channel", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@beauty-mania-house", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@SHISEIDOofficial", "categories" => %w(beauty other)},
    {"url"=>"https://www.youtube.com/@shiseido.beauty.journey", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@cosmemory", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@shushu_223_", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@BMYuya", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@arichan_make", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@aicachannel", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@shokobeautych", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kaorimake", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@_kiiigram_", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kajieri", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@melt__in", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@RaytenorJp", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@fullbody777", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kyon7699", "categories" => %w(beauty lifehack)},
    {"url"=>"https://www.youtube.com/@biteki_com", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@harukamakeup", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@bihadado", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@saechannelofficial3375", "categories" => %w(beauty necessity tour)},
    {"url"=>"https://www.youtube.com/@ALISA-nh8hq", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@aicachannel", "categories" => %w(beauty necessity)},
    {"url"=>"https://www.youtube.com/@MimiTV_official", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@Yuchannel_cosme", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@rihominami", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@kapo_025", "categories" => %w(beauty necessity)},
    {"url"=>"https://www.youtube.com/@SYKMAKEUP", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@dreamoon_hm", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@shabon_official", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@june1978", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@airi_official", "categories" => %w(beauty necessity)},
    {"url"=>"https://www.youtube.com/@momotao1021", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@yukikirei", "categories" => %w(beauty other)},
    {"url"=>"https://www.youtube.com/@kayodoll38", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@tamukun_36", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@garuchan_news", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@dan.beauty", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@memeron_me", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@yt.hitomi", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@makotomaishi", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@user-vh5zv7tp8p", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@misakimakeup", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@Dr.Akaken", "categories" => %w(beauty)},
    {"url"=>"https://www.youtube.com/@biyouseitai-uchiyama", "categories" => %w(beauty health)},
    {"url"=>"https://www.youtube.com/@Mitoma_Makeup", "categories" => %w(beauty womens_fashion)},
    {"url"=>"https://www.youtube.com/@aoi_ihara", "categories" => %w(beauty womens_fashion tour)},
    {"url"=>"https://www.youtube.com/@kei_adrer", "categories" => %w(beauty mens_faashion necessity)},
    {"url"=>"https://www.youtube.com/@SHELTTER_TV", "categories" => %w(beauty womens_fashion necessity)},
    {"url"=>"https://www.youtube.com/@emk_oooo", "categories" => %w(beauty necessity item)},
    

    {"url"=>"https://www.youtube.com/@baycrews_official", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@rinkachannel", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@cospashionyurie", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@personal-stylist", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@KANAKO", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@kayokolife", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@-woodyhouse-6110", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@wakasachannel", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@yukojunkoch", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@kyoko_kkfashion", "categories" => %w(womens_fashion other)},
    {"url"=>"https://www.youtube.com/@rena_yoshitsugu", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@user-cx7pn8pb6o", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@ulu-mai-yoko", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@kana__fashion", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@mari-colore", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@RYOKAchannel", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@takubokarin", "categories" => %w(womens_fashion beauty cooking)},
    {"url"=>"https://www.youtube.com/@yulano_official", "categories" => %w(womens_fashion beauty necessity)},
    {"url"=>"https://www.youtube.com/@hitomin3388", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@coco.", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@wakikodayo", "categories" => %w(womens_fashion beauty female_love necessity)},
    {"url"=>"https://www.youtube.com/@rina.", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@hitomin3388", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@rchaaaan", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@sarakordi0622", "categories" => %w(womens_fashion beauty tour)},
    {"url"=>"https://www.youtube.com/@minamiseto", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@_yuzuki22", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@rinateen_max", "categories" => %w(womens_fashion necessity)},
    {"url"=>"https://www.youtube.com/@saori_gokigenyo", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@hima_hima", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@SAKURA_Channel0808", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@mipomipo53", "categories" => %w(womens_fashion beauty necessity)},
    {"url"=>"https://www.youtube.com/@rinaty_0416", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@kogumamoe", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@kappa_channel_", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@mari_room", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@___cni__", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@miita8399", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@momohochannel5013", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@himari_hazuki", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@tanteichan", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@momochi661", "categories" => %w(womens_fashion beauty vlog)},
    {"url"=>"https://www.youtube.com/@Asami-Konno0507", "categories" => %w(womens_fashion beauty loving child_rasing)},
    {"url"=>"https://www.youtube.com/@kirimaruuu", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@shoealamode", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@luno_youtube", "categories" => %w(womens_fashion)},
    {"url"=>"https://www.youtube.com/@kathy_tan529", "categories" => %w(womens_fashion vlog womens_fashion diet cooking)},
    {"url"=>"https://www.youtube.com/@yui_yanagihashi", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@LifeHapisan", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@picaruuu", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@cancamofficial", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@emitube6830", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@miyuu_kotaka", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@oshipuri", "categories" => %w(womens_fashion beauty loving)},
    {"url"=>"https://www.youtube.com/@Maeda_Nozomi", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@user-qr8fq5pm2m", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@runa_kurusu", "categories" => %w(womens_fashion beauty vlog)},
    {"url"=>"https://www.youtube.com/@doublesoup_jp", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@haruchannel6599", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@kinakokkonew", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@airiiindondoko", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@kinpirasan", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@yo_kinoshita", "categories" => %w(womens_fashion vlog)},
    {"url"=>"https://www.youtube.com/@yuzuki2629", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@kinuchannell", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@__nitamago__", "categories" => %w(womens_fashion beauty diet)},
    {"url"=>"https://www.youtube.com/@pu_san1121", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@neni2233", "categories" => %w(womens_fashion beauty)},
    {"url"=>"https://www.youtube.com/@seikafuruhata9834", "categories" => %w(womens_fashion beauty)},

    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@masaki_wear", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},
    {"url"=>"https://www.youtube.com/@chuchudanshi", "categories" => %w(mens_faashion)},

    {"url"=>"https://www.youtube.com/@MarinaTakewaki", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@tabiwadance", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@user-wg1mh5jr4x", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@naru.enjoy_diet", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@chillyogadiet3511", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@yoshi-koba", "categories" => %w(health)},
    {"url"=>"https://www.youtube.com/@NiceEar", "categories" => %w(health)},
    
    {"url"=>"https://www.youtube.com/@user-jk1yu2mw8e", "categories" => %w(health finance education business)},


    {"url"=>"https://www.youtube.com/@yoshi-koba", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@TBSSPORTS6", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@DaisukeNasu", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@user-bd4wn4jc5k", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@DAZNJapan", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@SPOTVNOWJAPAN", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@SPOTV_NEWS", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@user-bd4wn4jc5k", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@user-bd4wn4jc5k", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@nyankoattack", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@ntvsports", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@tvtokyosports", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@ultra-sports", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@TV-pc3hb", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@jsports", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@tbs5947", "categories" => %w(sports track), 'absolute' => %w(sports track)},
    {"url"=>"https://www.youtube.com/@Bballnews2for1", "categories" => %w(sports)},
    {"url"=>"https://www.youtube.com/@SPOTVNOWJAPAN", "categories" => %w(sports soccer baseball), 'absolute' => %w(sports)},
    {"url"=>"https://www.youtube.com/@SPOTVNOWJAPAN", "categories" => %w(sports soccer baseball), 'absolute' => %w(sports)},
    {"url"=>"https://www.youtube.com/@SPOTVNOWJAPAN", "categories" => %w(sports soccer baseball), 'absolute' => %w(sports)},
    {"url"=>"https://www.youtube.com/@ldx9999", "categories" => %w(sports soccer baseball), 'absolute' => %w(sports)},

    {"url"=>"https://www.youtube.com/@jfa", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@user-hf2me2sl1z", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@RonassiComps", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@user-hf2me2sl1z", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@ABEMA_soccer", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@2ch-soccer-jyouhoukan", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@anvilbro8417", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@GOATfootballtactics", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@wowowofficial3688", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@FR24_", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@uwasathefootball", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@SDIA", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@frontalechannel", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@UNEXT_football", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@soccerkingdom", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@chch-cb4bz", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@j2ch-kw2zg", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@football2ch5ch", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@syukanbunsyundenshiban", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@Football-di5yb", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@momospo", "categories" => %w(soccer)},
    {"url"=>"https://www.youtube.com/@SDIA", "categories" => %w(soccer)},

    {"url"=>"https://www.youtube.com/@Mekkley", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@HochiProyakyuCH", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@goo-touchchannel", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@daida-no-kamisama", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@sportsnavi_baseball", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@toraban", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@jsports_yakyu", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@user-up7gu3dm9w", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@carp-kachiguse", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@ntv_baseball", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@toratora_tigers", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@mlb_honyaku", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@samuspo", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@ch-uf3fm", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@chch-gx3bf", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@chibalotte", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@YOMIURI_GIANTS", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@toraban", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@enjoy_koshien", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@professional_baseball_cam", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@PacificLeagueTVofficial", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@yanatakachannel", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@SBHawksOfficial", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@NPB.official", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@buffaloestv", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@Yakult-swallowsCoJp", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@tamamon3196", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@FIGHTERSofficial", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@lions", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@PacificLeagueMovie", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@2ch5chch", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@kotobukinzify", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@ohtanibaseman", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@user-ly1ue6pb9i", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@700man", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@msmmlbshotimemedia922", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@baseball.news.channel", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@BigfanofShoheiOhtanilye", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@user-sy7ht8uz8s", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@Movie_Bay", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@BellTVyoutube", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@baystars_diary1998", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@yakyumeikan", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@baystarsofficial", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@thecardswatcher", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@user-ib3pk8ef2i", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@OHTANISyoTime", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@FRANCHSEACADEY", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@BaseballkingJP", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@ramjam51", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@prosports_TV", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@tvar3375", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@2ch5ch11", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@user-ro4jp7jd6n", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@base-ballnews", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@komogomoTVshorts", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@baseballdiary", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@qooninTV", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@gsbaseballtv", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@2023WBC", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@CHUNICHI_DRAGONS", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@hanshintigers_official", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@MikanCH", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@ChillnDrive", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@presidentbaseball", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@teriyakitimes", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@800man", "categories" => %w(baseball)},
    {"url"=>"https://www.youtube.com/@KenshinCutterChannel", "categories" => %w(baseball)},
    

    {"url"=>"https://www.youtube.com/@NipponFoundationPR", "categories" => %w(documentary)},
    {"url"=>"https://www.youtube.com/@cbc_docu", "categories" => %w(documentary)},
    {"url"=>"https://www.youtube.com/@gairokuch", "categories" => %w(documentary)},
    {"url"=>"https://www.youtube.com/@yoshi-koba", "categories" => %w(documentary)},
    

    {"url"=>"https://www.youtube.com/@TBS_geino", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@mynavinews-entame", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@shuntyantv", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@JIJIPRESS", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@user-gz7vk2um3w", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@kyodonews_ent", "categories" => %w(entertainmet)},
    {"url"=>"https://www.youtube.com/@yoshi-koba", "categories" => %w(documentary)},

    {"url"=>"https://www.youtube.com/@moteki", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@kamin_zzz", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@rabuteku", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@user-cf1cm8pf4d", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@nayamerukohitsuji233", "categories" => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@user-hf2qv6hx9r", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@tokky_waseda_mental", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@saekipointy", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@aki_sinkon", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    #{"url"=>"https://www.youtube.com/@user-kv6mf7fw6", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@yoshio_and_aika", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@arano-moteki", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@syukukashi", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@aranosankirinuki", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@sekuteku", "categories" => %w(male_love female_love), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@user-rl9cx8bs1o", "categories" => %w(male_love female_love other), 'absolute' => %w(male_love female_love)},
    {"url"=>"https://www.youtube.com/@emi.hirose", "categories" => %w(male_love female_love psychology), 'absolute' => %w(male_love female_love)},

    {"url"=>"https://www.youtube.com/@moteotv", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@HikikomoriKyabajo", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-kc3vh7zs5u", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@rennai-yuri", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@love_lab_pug", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-pz1th2vx7i", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-ry6hb1bc8s", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@jurich6936", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@sumire.fujisaki", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-hd1pl6ro9g", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@makinoheya", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@morikawayosuke", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-yj2rv2jw3j", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@dr.zumin.", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@haredesu_9", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@you9737", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@yuru-ri", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@attractionuniv", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@mamisensei", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-jg2jr6kp7l", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@namitube", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@ch-hb4wi", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@otokonomondai", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-uw1vj5gg7s", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@rietv8602", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-ev7zh8vp4u", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@yuru-ri", "categories" => %w(male_love)},
    {"url"=>"https://www.youtube.com/@user-uw2qo3ni7b", "categories" => %w(male_love)},

    {"url"=>"https://www.youtube.com/@komasantarot", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@koibana_time", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@user-gt5cj4vn3d", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@tomohirokawase", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@syukurou", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@Yuuu-rs", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@yokichannel", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@koikatsu_room", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@ryuki_love369", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@user-li5zq6lb7x", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@haipa-okinntama", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@koutamcbrown", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@ilty01", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@damasarenai", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@toma_channel", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@kindan_no_kajitsu", "categories" => %w(female_love)},
    {"url"=>"https://www.youtube.com/@momopurizm", "categories" => %w(female_love other)},

    {"url"=>"https://www.youtube.com/@furinkaikethu", "categories" => %w(merrage)},

    {"url"=>"https://www.youtube.com/@ryotaro0922", "categories" => %w(love psychology)},
    {"url"=>"https://www.youtube.com/@naresome_yobiko", "categories" => %w(love psychology)},
    {"url"=>"https://www.youtube.com/@ningen-toribia", "categories" => %w(love psychology)},
    

    {"url"=>"https://www.youtube.com/@lucky-panda", "categories" => %w(psychology)},
    
    {"url"=>"https://www.youtube.com/@Variety_ABEMA", "categories" => %w(variety)},


    {"url"=>"https://www.youtube.com/@bellebook", "categories" => %w(novel)},
]